### ISSUE TITLE
Updating to 3.7.2 breaks push notifications

### ISSUE THREAD

**Issue by androuis** [Accengage/accengage-android-sdk-samples#9]
Updating to 3.7.2 does not work anymore when it comes to receiving push notifications. Also, as a note, when I call getIDFV() I receive in onResult a null string.
I updated from version 3.5.2 and did the following:
- removed  android:name="com.ad4screen.sdk.A4SService" from manifest
- added implementation 'com.ad4screen.sdk:plugin-firebase-messaging:2.3' in build.gradle
- added strings:
    `<string name="acc_partner_id" translatable="false">SOME_VALUE</string>`
    `<string name="acc_private_key" translatable="false">SOME_VALUE</string>`
    `<string name="acc_notification_accent_color">#99b841</string>`
    `<string name="acc_notification_icon">system_icon</string>`
    `<string name="acc_sender_id">gcm:SOME_VALUE</string>`
    `<string name="acc_unsecure_push">false</string>`
    `<string name="acc_logging">true</string>`
    `<string name="acc_no_geoloc">true</string>`
    `<string name="acc_optin_data">true</string>`

Am I missing anything?

**Comment by Ulrico972** [comment]
Hi,
I think you are missing this part of the documentation : http://docs.accengage.com/display/AND/2.3.+Updating+the+SDK+version

**Comment by Ulrico972** [comment]
Hi,
I think you are missing this part of the documentation : http://docs.accengage.com/display/AND/2.3.+Updating+the+SDK+version

**Comment by androuis** [comment]
Yes, sorry, actually the problem was on my side...after i modified the sender id, everything worked.
